name: Plasma acceleration explained in Plain English
markdown: redcarpet
pygments: false
encoding: utf-8
exclude: [Gemfile, Gemfile.lock, .gitignore, README.md, urls.txt]
markdown: kramdown

kramdown:
  auto_ids: true
